apiVersion: v1
kind: Pod
metadata:
  name: my-script-test-pod
spec:
  containers:
  - name: my-script-container
    image: ttldlinhtm/my-script:latest
    command: ["sh", "-c", "echo 'Hello from my-script on NFS' > /mnt/testfile && sleep 3600"]
    volumeMounts:
    - mountPath: /mnt
      name: nfs-volume
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-pvc
